#-------------------------------
# Site Settings
title: 
logo:
description: 
color_scheme: dark # auto, light, or dark

#-------------------------------
# Navigation Settings
menu__settings:
  menu__items:
    - title: 'Home'
      url: '/'
    - title: 'Work'
      url: '/work/'
    - title: 'Projects'
      url: '/projects/'
    - title: 'Blog'
      url: '/blog/'
    - title: 'About'
      url: '/about/'
    # - title: 'Pages'
    #   submenu:
    #   - url: '/contact/'
    #     title: 'Contact'
    #   - url: '/elements/'
    #     title: 'Elements'

#-------------------------------
# Author Settings
author:
  author__name: Hyungjin Shin
  author__bio:

social:
- {icon: "ion-logo-linkedin", link: "https://www.linkedin.com/in/hyungjin-shin-481607170/"}
- {icon: "ion-logo-github", link: "https://github.com/hs-pp"}

#-------------------------------
# Hero Settings
hero:
  enable: true
  hero__icon: '/images/portfolio/accampfire.png'
  hero__title: Hyungjin Shin
  hero__description: 10 years in the industry with some cool things to show for it.

#-------------------------------
# Work Settings
work:
  enable: true
  work__title: Professional Work
  work__description: Opportunities I've been a part of in my career.
  work__description_long:

#-------------------------------
# Projects Settings
projects:
  enable: true
  projects__title: Personal Projects
  projects__description: Personal projects I've done on my free time.
  projects__description_long:

#-------------------------------
# Blog Section
blog:
  enable: false

blog__settings:
  blog__title: Blog
  blog__description:

#-------------------------------
# Footer Settings
footer__background__image: '/images/portfolio/accampfire.png'

#-------------------------------
# Google Analytics
google-analytics: 'G-C7965CW3DB' # Add your GA Tracking Id

#-------------------------------
# Newsletter
mailchimp:
  enable: false
  mailchimp__identifier: frnla.us6.list-manage.com/subscribe/post?u=6314d69a3f315af7ce3fb00a0&amp;id=3038727cc3 # Add your MailChimp form identifier. For example - frnla.us6.list-manage.com/subscribe/post?u=6314d69a3f315af7ce3fb00a0&amp;id=3038727cc3
  mailchimp__input__text: Your email address...
  mailchimp__button__text: Subscribe

#-------------------------------
